export default {
  '1': require('../../assets/weatherIcon/128px/1.png'),
  '1n': require('../../assets/weatherIcon/128px/1n.png'),  
  '2': require('../../assets/weatherIcon/128px/2.png'),
  '2n': require('../../assets/weatherIcon/128px/2n.png'),    
  '2r': require('../../assets/weatherIcon/128px/2r.png'),  
  '2rn': require('../../assets/weatherIcon/128px/2rn.png'),
  '3': require('../../assets/weatherIcon/128px/3.png'),
  '3n': require('../../assets/weatherIcon/128px/3n.png'),
  '3tm': require('../../assets/weatherIcon/128px/3TM.png'),
  '4': require('../../assets/weatherIcon/128px/4.png'),
  '4n': require('../../assets/weatherIcon/128px/4n.png'),
  '4r': require('../../assets/weatherIcon/128px/4r.png'),
  '4rn': require('../../assets/weatherIcon/128px/4rn.png'),
  '4t': require('../../assets/weatherIcon/128px/4t.png'),
  '4tn': require('../../assets/weatherIcon/128px/4tn.png'),
  '5': require('../../assets/weatherIcon/128px/5.png'),
  '5n': require('../../assets/weatherIcon/128px/5n.png'),
  '6': require('../../assets/weatherIcon/128px/6.png'),
  '6n': require('../../assets/weatherIcon/128px/6n.png'),
  '7': require('../../assets/weatherIcon/128px/7.png'),
  '7n': require('../../assets/weatherIcon/128px/7n.png'),
  '8': require('../../assets/weatherIcon/128px/8.png'),
  '9': require('../../assets/weatherIcon/128px/9.png'),
  '9n': require('../../assets/weatherIcon/128px/9n.png'),
}